iiname: 'SSH4Me'
author: 'jisan09'
description: 'Build SSH tunnel using ngrok over workflow'

runs:
  using: 'composite'
  steps:
    - name: 'Set up Docker'
      shell: bash
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh

    - name: 'Build Docker image'
      shell: bash
      run: |
         
+50
It is not something about order. The Dockerfile must be specified with -f

     run: |
        docker build -t ssh4me --mode=max --build-arg AUTH_TOKEN=$AUTH_TOKEN --build-arg PASSWORD=$PASSWORD .
    - name: 'Run Docker container'
      shell: bash
      run: docker run-it --privileged  docker.io/library/ssh4me BENCHMARK="import timeit; print(timeit.timeit('list(range(10000))', number=50000))"
        python3.11 -c "$BENCHMARK"
  

branding:
  icon: 'terminal'
  color: 'gray-dark'
