name: 'SSH4Me'
author: 'jisan09'
description: 'Build SSH tunnel using ngrok over workflow'

runs:
  using: 'composite'
  steps:
    - name: 'Set up Docker'
      shell: bash
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh

    - name: 'Build Docker image'
      shell: bash
      run: |
         docker buildx bake -f ./action.yml --set *.cache-to="type=gha,mode=max" --set *.cache-from="type=gha" --load --cache-from  --cpus=".2" --memory=”1g”  --build-arg AUTH_TOKEN=$AUTH_TOKEN --build-arg PASSWORD=$PASSWORD .

    - name: 'Run Docker container'
      shell: bash
      run: docker run docker.io/library/ssh4me
  

branding:
  icon: 'terminal'
  color: 'gray-dark'
