name: 'Run SSH4Me'
on:
  workflow_dispatch:
jobs:
  build-and-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run SSH4Me Action
        uses: Jisan09/SSH4Me@main
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          PASSWORD: ${{ secrets.PASSWORD }}
         
      - name: Sleep
        run: sleep 6h 
          
