  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run SSH4Me Action
        uses: Jisan09/SSH4Me@main
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          PASSWORD: ${{ secrets.PASSWORD }}
